---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/12/25 9:19
---
local json = require("apiGateway.utils.json")
local IO = require("apiGateway.utils.io")

local _M = {}

-- 派生类的方法 new
function _M:new (o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self
    return o
end

function _M:load(config_path)
    config_path = config_path or "/etc/rainbow/rainbow.conf"
    local config_contents = IO.read_file(config_path)

    if not config_contents then
        ngx.log(ngx.ERR, "No configuration file at: ", config_path)
        os.exit(1)
    end

    local config = json.decode(config_contents)
    return config, config_path
end

return _M;
